name: CI
on: [push]
jobs:
  build-qq-ci:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Build
      uses: docker://qqminiapp/build:1.0.0
      env:
        PLUGIN_VERSION: 1.5.8
        PLUGIN_DESC: CI自动构建上传1111
        PLUGIN_APPTOKEN: b1dc5aab833af6a21118bbfa10e82f64
        PLUGIN_BUILDUSER: ${ GITHUB_ACTOR }
        PLUGIN_EXPERIENCE: true

