name: CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build-qq-ci:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Build
      uses: docker://qqminiapp/build:latest
      env:
        PLUGIN_VERSION: 1.5.9
        PLUGIN_DESC: CI自动构建上传
        PLUGIN_APPTOKEN: ${{ secrets.APPTOKEN }}
        PLUGIN_BUILDUSER: ${{github.actor}}
        PLUGIN_EXPERIENCE: true
        PLUGIN_NPMBUILD: true

