workflow "Build" {
  on = "push"
  resolves = ["Build"]
}

action "Build" {
  uses = "qq-miniapp/build:latest"
  env = {
    VERSION="1.5.8"
    DESC="CI自动构建上传"
    APPTOKEN="b1dc5aab833af6a21118bbfa10e82f64"
    BUILDUSER=${ GITHUB_ACTOR }
    EXPERIENCE=true
  }
}
